### ISSUE TITLE
[TroubleShooting - CL] - 도커 CI/CD 배포

### ISSUE THREAD

**Issue by younghak9905** [100-hours-a-week/2-hertz-wiki#242]
# [2025-05-27] 도커 CI/CD 배포

## 🐞 에러 내용
	- AI 서버 Docker 이미지의 크기가 지나치게 커져서 ECR 업로드 및 배포 시간이 길어짐 (최대 10GB)
	- ECR 저장소의 용량도 빠르게 소모되어, 도커 배포의 이점(경량화·빠른 롤백·신속한 배포)이 사라짐

## 🔍 원인 분석
	- AI 모델 파일과 무거운 Python 라이브러리(예: sentence-transformers, torch 등)가 이미지 내부에 포함되어 용량이 대폭 증가.
	- 이미지를 빌드할 때마다 불필요하게 대용량 파일이 포함되어, ECR push/pull 속도가 저하되고, 저장소 용량 관리도 어려워짐.
	- 여러 대안 시도:
	1.	AI 모델을 분리하여, 최초 import 시 서버에서 직접 다운로드하도록 변경했으나, 이미지 크기에 큰 영향을 주지는 않음.
	2.	Base 이미지를 업로드하고, 무거운 라이브러리는 배포 시 서버에서 별도 설치하여 재빌드하는 방법도 시도.
→ 하지만 base 이미지가 변경되면, 라이브러리 재설치로 인해 빌드 캐싱 효과가 없음.

## ✅ 해결 방법
	- 무거운 라이브러리는 서버에서 최초 1회만 직접 설치하거나, 별도의 디렉터리(/home/deploy/app-pylibs 등)에 다운로드 후, 도커 컨테이너 실행 시 볼륨 마운트(-v /home/deploy/app-pylibs:/app/extlibs) 방식으로 사용.
	- Dockerfile의 PYTHONPATH를 /app:/app/extlibs로 설정해, 마운트된 경로의 라이브러리를 인식하도록 함.
	- 배포 시에는 실제 코드와 가벼운 의존성만 포함된 이미지로 빌드하여 ECR push/pull 속도 및 용량 문제를 해결.
   

## 🤔 회고
 	- AI 모델/대용량 라이브러리는 도커 이미지에서 분리하는 것이 유지보수와 배포 효율성 면에서 현명하다는 것을 경험함.
	- ECR의 저장 용량, push/pull 속도, 배포 시간 단축 등 실제 운영 효율성이 크게 개선됨.
	- 단순히 이미지 경량화뿐 아니라, 배포 파이프라인에 맞는 볼륨 마운트 전략과 환경 변수 관리가 중요함을 체감.

1. 최적화된 Dockerfile 예시
```yaml
FROM python:3.10-slim

# 작업 디렉토리 지정
WORKDIR /app

RUN pip install --upgrade pip setuptools wheel

# requirements-base.txt만 복사 (캐시 최대 활용)
COPY ./app-tuning/requirements-base.txt /app/requirements-base.txt

# 의존성 설치 (최소 requirements만) (무거운 라이브러리 제외)
RUN pip install --no-cache-dir -r /app/requirements-base.txt

# 앱 소스 복사 (최대한 마지막에! 코드 변경 시 캐시 최대화)
COPY ./app-tuning /app

RUN mkdir -p /app/model-cache

# 환경 변수 설정 . . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

2. docker-compose 볼륨 마운트 예시
```yaml
services:
  tuning:
    container_name: tuning
    image: ${FULL_IMAGE}
    volumes:
      - /home/deploy/app-pylibs:/app/extlibs   <- 라이브러리를 서버에 받아 놓고 마운트
      - tuning_logs:/app/logs
      - /home/deploy/models:/app/model-cache <- 모델을 이미지와 분리하여 마운트
    ports:
      - "8000:8000"
    # ...기타 설정 생략
volumes:
  tuning_logs:
```
3. 배포 스크립트(서버에서 무거운 라이브러리/모델 설치)
```bash
# sentence-transformers 패키지 자동 설치 (없을 때만)
PYLIBS_DIR="/home/deploy/app-pylibs"
if [ ! -d "$PYLIBS_DIR/sentence_transformers" ]; then
  echo "📦 sentence-transformers 패키지가 없으므로 설치합니다..."
  mkdir -p "$PYLIBS_DIR"
  pip install --upgrade pip
  pip install --target="$PYLIBS_DIR" sentence-transformers==4.1.0
else
  echo "✅ sentence-transformers 패키지가 이미 존재합니다."
fi

# 모델 캐시 자동 다운로드
if [ ! -d "/home/deploy/models/jhgan-ko-sbert-nli" ]; then
  echo "모델 디렉토리가 없습니다. 모델을 먼저 다운로드합니다."
  docker compose -f docker-compose-tuning run --rm tuning python scripts/download_model.py
else
  echo "모델 디렉토리가 이미 존재합니다. 다운로드를 건너뜁니다."
fi

docker compose -f docker-compose-tuning.yml stop tuning
docker compose -f docker-compose-tuning.yml rm -f tuning
docker compose --env-file .env -f docker-compose-tuning.yml up -d tuning
```

이러한 방식으로 실제 서버에는 aws cli와 도커만 설치 되어 있다면 실행 가능하도록 하였습니다.
