### ISSUE TITLE
[TroubleShooting -CL] - 도커 CI/CD worksflow

### ISSUE THREAD

**Issue by younghak9905** [100-hours-a-week/2-hertz-wiki#243]
# [2025-05-27] 도커 CI/CD worksflow

## 🐞 에러 내용
- Job 간 환경변수/Output 전달 실패
- 첫 번째 Job에서 생성한 이미지 태그, ECR 레지스트리 정보 등 주요 변수들이 다음 Job에서 제대로 사용되지 않음.
- 민감 정보(SSH Key) 전달 실패
- Job 내에서 GITHUB_ENV에 등록한 SSH key 경로가 다음 Job에서 인식되지 않아, SSH 연결 시도 시 ssh: no key found 에러 발생.
	- Output을 통한 민감 정보 전달 제한
	- outputs로 선언한 값 중 민감 정보(예: Secret)는 노출 또는 전달이 차단됨.
	- SSH Key가 최초 1회만 정상 작동, 이후엔 인식 불가
	- load_secret_to_file로 생성한 파일이 job 경계(=runner 종료)에서 소실되어, 다음 Job의 SSH Action에서 Key 파일을 찾지 못하는 문제.

## 🔍 원인 분석
	- Job 간 환경 변수 전달 한계
	•	GitHub Actions의 env:는 동일 job 내에서만 유효하며, job 간 전달에는 outputs를 명시적으로 활용해야 함.
	•	하지만, 민감 정보(Secrets)는 outputs로 직접 전달하거나 표출이 불가하도록 제한되어 있음.
	•	Secret/파일의 job간 소실
	•	각 job은 독립된 VM/컨테이너 환경에서 실행되므로, 이전 job에서 만든 파일(SSH key 등)은 다음 job으로 직접 전달 불가.
	•	SSH Key 인식 오류
	•	다음 job에서 key 파일을 찾지 못하거나, 퍼미션(600)이 맞지 않거나, key 내용이 올바르게 전달되지 않음.

## ✅ 해결 방법
Output을 통한 환경 변수 명확화
	•	민감하지 않은 값은 아래처럼 outputs로 선언, needs로 연결해 전달.
```yaml
# job1 (빌드)
outputs:
  image_tag: ${{ steps.generate-tags.outputs.image_tag }}
  full_image: ${{ steps.generate-tags.outputs.full_image }}
  # ... 등

# job2 (배포)
needs: ci
run: |
  echo "IMAGE_TAG=${{ needs.ci.outputs.image_tag }}"
```

## 🤔 회고
	•	GitHub Actions는 Job 간 환경 변수, 파일, Secret 전달이 명확하게 분리되어 있다는 점을 실전에서 체감.
	•	민감 정보는 output에 노출될 수 없으므로, Secret은 매 Job마다 새로 세팅하는 구조로 만들어야 신뢰성이 높아짐.
	•	*SSH Key와 같이 job 내 임시 파일로 쓰이는 민감 정보는, 항상 “직접 생성” & “권한 부여(600)”*로 습관화.
	•	Output/Needs를 통한 변수 전달은 단순하지만, Security context에 따라 제한됨을 반드시 명심할 것.
	•	배포 자동화 스크립트에서 환경 변수, Secret, Output의 Life Cycle/스코프를 명확히 설계해야 CI/CD 파이프라인이 안정적임을 깨달음.
