### ISSUE TITLE
[TroubleShooting - CL] - Github Actions job에서 오류가 날 경우, 다음 job이 실행되지 않는 오류

### ISSUE THREAD

**Issue by DDongu** [100-hours-a-week/2-hertz-wiki#276]
# [2025-06-04] Github Actions job에서 오류가 날 경우, 다음 job이 실행되지 않는 오류

## 🐞 에러 내용
- Github Actions에서 CD job과 Rollback job을 구현함에 있어서, CD job이 실패할 경우 Rollback job이 실행되도록 다음과 같이 구현했다.
```yaml
  backend-rollback:
    needs: backend-cd
    if: needs.backend-cd.result != 'success'
```

이때 앞선 job인 backend-cd job이 실패한 경우, exit 1로 job이 끝나며 다음 job인 rollback으로 넘어가지 않았다. 
오류를 발생시키지 않기 위해 exit 0으로 끝낼 시에는, job이 성공한 것으로 인식되어 이것 또한 올바른 해결책이 아니었다.

## 🔍 원인 분석
- exit 1로 끝내거나 오류가 나면(이 경우에도 exit 1로 끝남), 해당 job이 끝남과 동시에 workflow를 무조건 종료하게 된다.
- 따라서 다음 job을 수행하는 조건에 어떤 `needs.backend-cd.result != 'success'`나 `needs.backend-cd.output.result == 'failure'`과 같은 다른 조건을 넣어도 무시되고 종료된다.

## ✅ 해결 방법
- job을 실행하는 조건문 중에 `always()`라는 조건문이 있다. 해당 조건문은 전 job의 종료 유무와 상관없이, 해당 job을 무조건 실행하게 하는 조건문이다. 따라서 다음과 같이 && 연산자와 함께 작성하면 의도한대로 rollback job을 실행시킬 수 있다.

```yaml
  backend-rollback:
    needs: backend-cd
    if: always() && needs.backend-cd.result != 'success'
```

## 🤔 회고
- 이번 트러블슈팅을 해결하면서 생성형 AI를 많이 사용했었는데, 공식문서 상에서 나오지 않는 해결책이 많아 생성형 AI로는 해결하는데 어려움이 많았다.
- 결국 직접적인 구글링을 통해서 stack overflow나 reddit을 참고하여 해결하였는데, 아직까지 많이 사용하지 않는 기술에 대해서는 AI로 한계가 있고, 직접적인 구글링이 필요하다는 것을 깨닳았다.
