### ISSUE TITLE
[TroubleShooting - CL] - Terraform CLI에서 JSON 형태의 변수 전달 시 발생하는 오류

### ISSUE THREAD

**Issue by DDongu** [100-hours-a-week/2-hertz-wiki#301]
# [2025-06-05] Terraform CLI에서 JSON 형태의 변수 전달 시 발생하는 오류

## 🐞 에러 내용

Terraform CLI에서 JSON 형태의 변수를 아래와 같이 전달할 때 오류가 남

```yaml
      - name: Deploy to Next Environment
        working-directory: tf-code/terraform/gcp/environments/prod
        run: |
          terraform apply -auto-approve \
            -var="docker_image_frontend_${{ steps.color.outputs.target }}=${{ env.IMAGE }}" \
            -var="${{ steps.color.outputs.target }}_instance_count={\"desired\":1,\"min\":1,\"max\":2}"
```

## 🔍 원인 분석
- Terraform CLI를 통해 apply를 할 때, JSON 문자열을 -var 옵션을 통해 바로 넘기면 문자열 파싱에 오류가 생겨 일반 문자열로 처리하려한다. 따라서 `\"`를 `"`가 아닌 문자 그대로 `\"`로 인식하게 된다.

## ✅ 해결 방법
- actions에서 `.auto.tfvars.json` 파일을 만들고, 그 안에 json 데이터를 넣는 방식으로 변수를 대입한다.

```yaml
       - name: Write tfvars file for next deployment
        working-directory: tf-code/terraform/gcp/environments/prod
        run: |
          TARGET=${{ steps.color.outputs.target }}
          echo "{" > deployment.auto.tfvars.json
          echo "  \"docker_image_frontend_${TARGET}\": \"${{ env.IMAGE }}\"," >> deployment.auto.tfvars.json
          echo "  \"${TARGET}_instance_count\": {\"desired\":1, \"min\": 1, \"max\": 2}" >> deployment.auto.tfvars.json
          echo "}" >> deployment.auto.tfvars.json

      - name: Deploy to Next Environment
        working-directory: tf-code/terraform/gcp/environments/prod
        run: terraform apply -auto-approve
```

## 🤔 회고
- 로컬 환경이나 GUI 환경과는 다르게 Actions에서는 스크립트로 CLI를 작성하다보니, 스크립트 내의 코드 파싱이나 변수 치환 방식 등이 겹쳐 혼동되는게 많았다.
- 스크립트를 작성할 때, 데이터를 특정 파일에 저장하여 사용하거나, 환경변수에 넣어 사용하는 등 데이터의 일관성을 유지할 수 있는 방법을 알 수 있었다.
